version: '3'

services:
  postgres:
    restart: always
    image: postgres:latest
    container_name: challenge
    environment:
      POSTGRES_PASSWORD: challenge
      POSTGRES_USER: challenge
      POSTGRES_DB: challenge
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  postgres-test:
    restart: always
    image: postgres:latest
    container_name: challenge-test
    environment:
        POSTGRES_PASSWORD: challenge-test
        POSTGRES_USER: challenge-test
        POSTGRES_DB: challenge-test
    volumes:
        - db-data-test:/var/lib/postgresql/data
    ports:
        - "5433:5432"        

volumes:
  db-data:
  db-data-test:
  redis-data:
