version: '3'

services:
  postgres:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: challenge
      POSTGRES_USER: challenge
      POSTGRES_DB: challenge
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:
